debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.project.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: jamsiman
    password: shvhsy8571@
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 100
      hibernate:
        format_sql: true
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3.decoupled-logic: true






